conts = {
    "Africa":{
        "Algeria":{"Cities":None},
        "Angola":{"Cities":None},
        "Benin":{"Cities":None},
        "Botswana":{"Cities":None},
        "Burkina Faso":{"Cities":None},
        "Burundi":{"Cities":None},
        "Cabo Verde":{"Cities":None},
        "Cameroon":{"Cities":None},
        "Central African Republic":{"Cities":None},
        "Chad":{"Cities":None},
        "Comoros":{"Cities":None},
        "Congo, Democratic Republic of the":{"Cities":None},
        "Congo, Republic of the":{"Cities":None},
        "Cote d'Ivoire":{"Cities":None},
        "Djibouti":{"Cities":None},
        "Egypt":{"Cities":None},
        "Equatorial Guinea":{"Cities":None},
        "Eritrea":{"Cities":None},
        "Eswatini":{"Cities":None},
        "Ethiopia":{"Cities":None},
        "Gabon":{"Cities":None},
        "Gambia":{"Cities":None},
        "Ghana":{"Cities":None},
        "Guinea":{"Cities":None},
        "Guinea-Bissau":{"Cities":None},
        "Kenya":{"Cities":None},
        "Lesotho":{"Cities":None},
        "Liberia":{"Cities":None},
        "Libya":{"Cities":None},
        "Madagascar":{"Cities":None},
        "Malawi":{"Cities":None},
        "Mali":{"Cities":None},
        "Mauritania":{"Cities":None},
        "Mauritius":{"Cities":None},
        "Morocco":{"Cities":None},
        "Mozambique":{"Cities":None},
        "Namibia":{"Cities":None},
        "Niger":{"Cities":None},
        "Nigeria":{"Cities":None},
        "Rwanda":{"Cities":None},
        "Sao Tome and Principe":{"Cities":None},
        "Senegal":{"Cities":None},
        "Seychelles":{"Cities":None},
        "Sierra Leone":{"Cities":None},
        "Somalia":{"Cities":None},
        "South Africa":{"Cities":None},
        "South Sudan":{"Cities":None},
        "Sudan":{"Cities":None},
        "Tanzania":{"Cities":None},
        "Togo":{"Cities":None},
        "Tunisia":{"Cities":None},
        "Uganda":{"Cities":None},
        "Zambia":{"Cities":None},
        "Zimbabwe":{"Cities":None},

    }, "Asia":{

        "Afghanistan":{"Cities":None},
        "Armenia":{"Cities":None},
        "Azerbaijan":{"Cities":None},
        "Bahrain":{"Cities":None},
        "Bangladesh":{"Cities":None},
        "Bhutan":{"Cities":None},
        "Brunei":{"Cities":None},
        "Cambodia":{"Cities":None},
        "China":{"Cities":None},
        "Cyprus":{"Cities":None},
        "Georgia":{"Cities":None},
        "India":{"Cities":None},
        "Indonesia":{"Cities":None},
        "Iran":{"Cities":None},
        "Iraq":{"Cities":None},
        "Israel":{"Cities":None},
        "Japan":{"Cities":None},
        "Jordan":{"Cities":None},
        "Kazakhstan":{"Cities":None},
        "Kuwait":{"Cities":None},
        "Kyrgyzstan":{"Cities":None},
        "Laos":{"Cities":None},
        "Lebanon":{"Cities":None},
        "Malaysia":{"Cities":None},
        "Maldives":{"Cities":None},
        "Mongolia":{"Cities":None},
        "Myanmar":{"Cities":None},
        "Nepal":{"Cities":None},
        "North Korea":{"Cities":None},
        "Oman":{"Cities":None},
        "Pakistan":{"Cities":None},
        "Palestine":{"Cities":None},
        "Philippines":{"Cities":None},
        "Qatar":{"Cities":None},
        "Russia":{"Cities":None},
        "Saudi Arabia":{"Cities":None},
        "Singapore":{"Cities":None},
        "South Korea":{"Cities":None},
        "Sri Lanka":{"Cities":None},
        "Syria":{"Cities":None},
        "Taiwan":{"Cities":None},
        "Tajikistan":{"Cities":None},
        "Thailand":{"Cities":None},
        "Timor-Leste":{"Cities":None},
        "Turkey":{"Cities":None},
        "Turkmenistan":{"Cities":None},
        "United Arab Emirates":{"Cities":None},
        "Uzbekistan":{"Cities":None},
        "Vietnam":{"Cities":None},
        "Yemen":{"Cities":None},

    }, "Europe":{

        "Albania":{"Cities":None},
        "Andorra":{"Cities":None},
        "Armenia":{"Cities":None},
        "Austria":{"Cities":None},
        "Azerbaijan":{"Cities":None},
        "Belarus":{"Cities":None},
        "Belgium":{"Cities":None},
        "Bosnia and Herzegovina":{"Cities":None},
        "Bulgaria":{"Cities":None},
        "Croatia":{"Cities":None},
        "Cyprus":{"Cities":None},
        "Czechia":{"Cities":None},
        "Denmark":{"Cities":None},
        "Estonia":{"Cities":None},
        "Finland":{"Cities":None},
        "France":{"Cities":None},
        "Georgia":{"Cities":None},
        "Germany":{"Cities":None},
        "Greece":{"Cities":None},
        "Hungary":{"Cities":None},
        "Iceland":{"Cities":None},
        "Ireland":{"Cities":None},
        "Italy":{"Cities":None},
        "Kazakhstan":{"Cities":None},
        "Kosovo":{"Cities":None},
        "Latvia":{"Cities":None},
        "Liechtenstein":{"Cities":None},
        "Lithuania":{"Cities":None},
        "Luxembourg":{"Cities":None},
        "Malta":{"Cities":None},
        "Moldova":{"Cities":None},
        "Monaco":{"Cities":None},
        "Montenegro":{"Cities":None},
        "Netherlands":{"Cities":None},
        "North Macedonia":{"Cities":None},
        "Norway":{"Cities":None},
        "Poland":{"Cities":None},
        "Portugal":{"Cities":None},
        "Romania":{"Cities":None},
        "Russia":{"Cities":None},
        "San Marino":{"Cities":None},
        "Serbia":{"Cities":None},
        "Slovakia":{"Cities":None},
        "Slovenia":{"Cities":None},
        "Spain":{"Cities":None},
        "Sweden":{"Cities":None},
        "Switzerland":{"Cities":None},
        "Turkey":{"Cities":None},
        "Ukraine":{"Cities":None},
        "United Kingdom":{"Cities":None},
        "Vatican City":{"Cities":None},

    }, "North America":{

        "Antigua and Barbuda":{"Cities":None},
        "Bahamas":{"Cities":None},
        "Barbados":{"Cities":None},
        "Belize":{"Cities":None},
        "Canada":{"Cities":None},
        "Costa Rica":{"Cities":None},
        "Cuba":{"Cities":None},
        "Dominica":{"Cities":None},
        "Dominican Republic":{"Cities":None},
        "El Salvador":{"Cities":None},
        "Grenada":{"Cities":None},
        "Guatemala":{"Cities":None},
        "Haiti":{"Cities":None},
        "Honduras":{"Cities":None},
        "Jamaica":{"Cities":None},
        "Mexico":{"Cities":None},
        "Nicaragua":{"Cities":None},
        "Panama":{"Cities":None},
        "Saint Kitts and Nevis":{"Cities":None},
        "Saint Lucia":{"Cities":None},
        "Saint Vincent and the Grenadines":{"Cities":None},
        "Trinidad and Tobago":{"Cities":None},
        "United States of America":{
            "Alabama":{"Cities":None},
            "Alaska":{"Cities":None},
            "American Samoa":{"Cities":None},
            "Arizona":{"Cities":None},
            "Arkansas":{"Cities":None},
            "California":{"Cities":None},
            "Colorado":{"Cities":None},
            "Connecticut":{"Cities":None},
            "Delaware":{"Cities":None},
            "District of Columbia":{"Cities":None},
            "Florida":{"Cities":None},
            "Georgia":{"Cities":None},
            "Guam":{"Cities":None},
            "Hawaii":{"Cities":None},
            "Idaho":{"Cities":None},
            "Illinois":{"Cities":None},
            "Indiana":{"Cities":None},
            "Iowa":{"Cities":None},
            "Kansas":{"Cities":None},
            "Kentucky":{"Cities":None},
            "Louisiana":{"Cities":None},
            "Maine":{"Cities":None},
            "Maryland":{"Cities":None},
            "Massachusetts":{"Cities":None},
            "Michigan":{"Cities":None},
            "Minnesota":{"Cities":None},
            "Mississippi":{"Cities":None},
            "Missouri":{"Cities":None},
            "Montana":{"Cities":None},
            "Nebraska":{"Cities":None},
            "Nevada":{"Cities":None},
            "New Hampshire":{"Cities":None},
            "New Jersey":{"Cities":None},
            "New Mexico":{"Cities":None},
            "New York":{"Cities":None},
            "North Carolina":{"Cities":None},
            "North Dakota":{"Cities":None},
            "Northern Mariana Islands":{"Cities":None},
            "Ohio":{"Cities":None},
            "Oklahoma":{"Cities":None},
            "Oregon":{"Cities":None},
            "Pennsylvania":{"Cities":None},
            "Puerto Rico":{"Cities":None},
            "Rhode Island":{"Cities":None},
            "South Carolina":{"Cities":None},
            "South Dakota":{"Cities":None},
            "Tennessee":{"Cities":None},
            "Texas":{"Cities":None},
            "US Virgin Islands":{"Cities":None},
            "Utah":{"Cities":None},
            "Vermont":{"Cities":None},
            "Virginia":{"Cities":None},
            "Washington":{"Cities":None},
            "West Virginia":{"Cities":None},
            "Wisconsin":{"Cities":None},
            "Wyoming":{"Cities":None},
            "States":True,
        },

    }, "Oceania":{

        "Australia":{"Cities":None},
        "Fiji":{"Cities":None},
        "Kiribati":{"Cities":None},
        "Marshall Islands":{"Cities":None},
        "Micronesia":{"Cities":None},
        "Nauru":{"Cities":None},
        "New Zealand":{"Cities":None},
        "Palau":{"Cities":None},
        "Papua New Guinea":{"Cities":None},
        "Samoa":{"Cities":None},
        "Solomon Islands":{"Cities":None},
        "Tonga":{"Cities":None},
        "Tuvalu":{"Cities":None},
        "Vanauatu":{"Cities":None}

    }, "South America" :{

        "Argentina":{"Cities":None},
        "Bolivia":{"Cities":None},
        "Brazil":{"Cities":None},
        "Chile":{"Cities":None},
        "Colombia":{"Cities":None},
        "Ecuador":{"Cities":None},
        "Guyana":{"Cities":None},
        "Paraguay":{"Cities":None},
        "Peru":{"Cities":None},
        "Suriname":{"Cities":None},
        "Uruguay":{"Cities":None},
        "Venezuela":{"Cities":None},

    }
}

# Print Main page
# print('# Parkour Team and Gym Locations - Continent List\n\n')

# for cont in conts:
#     print('## [%s](https://www.reddit.com/r/Parkour/wiki/%s)\n\n' % (cont, cont.replace(' ','-')))

# Print Sub Page
for cont in conts:
    print('# Parkour Team and Gym Locations - Country List for %s \n\n' % cont)
    print('[Contact the mods](https://www.reddit.com/message/compose/?to=/r/Parkour&subject=Location%20Submission) to add your team or local gym to this list.\n\nSubmissions must include the Country, State/Territory (if applicable), City, Team or Gym name, and a contact link. Individuals cannot register as a point of contact for safety reasons.\n\n')
    for ct in conts[cont]:
        print('## %s \n\n' % ct)
        if 'States' in ct:
            for st in conts[cont][ct]:
                if st is not "States":
                    print('### %s \n\n' % st)
                    if conts[cont][ct][st]["Cities"] is not None:
                        for city in st:
                            if city not in [None, "Cities"]:
                                print('#### %s \n\n' % city)
                                for team in city:
                                    print('- [%s](%s)' % (team,team.link))
        else:
            for city in conts[cont][ct]:
                if city not in [None, "Cities"]:
                    print('### %s \n\n' % city)
                    for team in city:
                        print('- [%s](%s)' % (team,team.link))


